version: '3.1'

services:

  mongo:
    image: mongo:3.6
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - mongo-network

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/test
    command: ["./main"]
    networks:
      - mongo-network

networks:
  mongo-network1:
    driver: bridge

# services:
#   mongodb: 
#     image: mongo:latest 
#     container_name: mongodb 
#     hostname: mongodb
#   volumes:
#     - ./mongodb/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro 
#     - mongodb-data: /data/db/
#     - mongodb- log:/var/log/mongodb/
#   env_file:
#     - .env
#   environment:
#     MONGO_INITOB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}


# mongo-init.js
# db - ab-getS1bl1ng0B(*got_db");
# environment:
# MONGO_INITOB_ROOT_USERNAME: S (MONGO_INITDB_ROOT_USERNAME)
# MONGO_INITDB_ROOT_PASSWORD: S(MONGO_INITDB_ROOT_PASSWORD)
# ports:
# "27017:27017"
# networks:
# - mongodb_network
# v db. CreateUser(k
# user: "jon_snow",
# pwd："yeritte.
# roses.
# role: readurite,
# do: cot do
# ]):
# db. croateCollection("got_seasons_collection"):
# mongo-express: Image: mongo-express: latest container_name: mongo-express restart: always
# environment:
# ME_CONFIG_MONGODB_ADMINUSERNAME: $(MONGO_INI TDB_ROOT_USERIAME)
# ME_CONFIG_MONGODB_ADMINPASSWORD: $(MONGO_INITDB_ROOT_PASSWORD)
# ME_CONFIG_MONGODB_PORT: 27017
# ME_CONFIG_MONGODB_SERVER: 'mongodb
# ME_CONFIG_BASICAUTH_USERNAME: $(MONGO_EXPRESS_USERNAME)
# ME_CONFIG_BASICAUTH_ PASSWORD: (MONGO_EXPRESS_ PASSWORD)
# ports:
# 8081:8081
# networks:
# - mongodb_network
# depends on:
# mongodb
# -env
# v db-@ot_seasons_collection.1nserthanyCl season: "1", year: "2011",
# episodes: [*
# >^…
# >……
# volumes: mongodb-data: driver: local
# name: mongo-data mongodb-log: driver: local
# name: mongo-log
# # MaggoDB Favironment
# MONGO_INITDB_ROOT_USERNAME=root
# HONGO_INITOB_ROOT_PASSWORD-password
# MONGO_EXPRESS_USERNAME=admin
# MONGO_EXPRESS_PASSWORD=password
# networks: mongodb_network: driver: bridge
# name: mongo-network